databases:
  - name: grocerymate
    plan: free
    databaseName: grocerymate
    user: grocerymate

services:
  - type: web
    plan: free
    name: grocerymate
    runtime: python
    pythonVersion: 3.13
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn grocerymate.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grocerymate
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: grocerymate.settings
