databases:
  - name: grocerymate
    plan: free
    databaseName: grocerymate
    user: grocerymate

services:
  - type: web
    plan: free
    name: grocerymate
    runtime: python
    pythonVersion: 3.13
    buildCommand: |
      pip install -r grocerymate/requirements.txt
      python grocerymate/manage.py collectstatic --no-input
      python grocerymate/manage.py migrate
    startCommand: gunicorn grocerymate.grocerymate.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grocerymate
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_SETTINGS_MODULE
        value: grocerymate.grocerymate.settings
