databases:
  - name: grocerymate
    plan: free
    databaseName: grocerymate
    user: grocerymate

services:
  - type: web
    plan: free
    name: grocerymate
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn grocerymate.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grocerymate
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
